version: "2"
services:
  registry:
    image: registry:2
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      VIRTUAL_HOST: ${VHOST}
      VIRTUAL_PATH: ~ /v2.*
    volumes:
      - ./data-registry:/var/lib/registry
      - ./data-auth:/auth
    networks:
      - proxy-tier
  ui:
    image: jc21/registry-ui
    environment:
      - NODE_ENV=production
      - REGISTRY_HOST=registry:5000
      - REGISTRY_USER=${REGISTRY_USER}
      - REGISTRY_PASS=${REGISTRY_PASS}
      - VIRTUAL_HOST=${VHOST}
      - VIRTUAL_PATH=/
    restart: on-failure
    networks:
      - proxy-tier

networks:
  proxy-tier:
    external: true
