version: '3.8'
services:
  registry:
    image: registry:2
    restart: always
    volumes:
      - ./registry-auth:/auth
      - ./registry-data:/var/lib/registry
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      VIRTUAL_PATH: ~ /v2
      LETSENCRYPT_HOST: ${VIRTUAL_HOST}
      VIRUTAL_PORT: 5000
      REGISTRY_STORAGE_DELETE_ENABLED: true
    networks:
      - proxy-tier
  registry-ui:
    image: jc21/registry-ui
    environment:
      REGISTRY_HOST: registry:5000
      REGISTRY_STORAGE_DELETE_ENABLED: true
      REGISTRY_USER: ${REGISTRY_USER}
      REGISTRY_PASS: ${REGISTRY_PASS}
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      LETSENCRYPT_HOST: ${VIRTUAL_HOST}
      VIRTUAL_PATH: /
    links:
      - registry
    restart: on-failure
    networks:
      - proxy-tier

networks:
  proxy-tier:
    external: true
