version: '3.8'
services:
  registry:
    image: registry:2
    restart: always
    volumes:
      - ./registry-auth:/auth
      - ./registry-data:/var/lib/registry
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      VIRTUAL_HOST: registry.loop.santiagodenicolas.com
      VIRUTAL_PORT: 5000
    networks:
      - proxy-tier

networks:
  proxy-tier:
    external: true
