version: '3.8'
services:
  hello1:
    image: nginxdemos/hello
    ports:
      - 8080:80
    networks:
      - proxy-tier
    environment:
      - VIRTUAL_HOST=loop.santiagodenicolas.com
      - VIRTUAL_PATH=/
  hello2:
    image: nginxdemos/hello
    ports:
      - 8081:80
    networks:
      - proxy-tier
    environment:
      - VIRTUAL_HOST=loop.santiagodenicolas.com
      - VIRTUAL_PATH=/hello2

networks:
  proxy-tier:
    external: true
